checks:
  php: true

build:
  project_setup:
    after:
      - mysql -u root -e "CREATE DATABASE taskbook CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
      - ./vendor/bin/doctrine orm:schema-tool:create
  tests:
    override:
      -
        command: ./vendor/bin/phpunit --coverage-clover=my-coverage-file
        coverage:
            file: my-coverage-file
            format: php-clover
  environment:
    php:
      version: '7.0'
      ini:
        'date.timezone': 'Europe/Kiev'
    mysql: '5.7'
    selenium: false
    redis: false
    postgresql: false